In [1]:
import pandas as pd
import networkx as nx
import json

In [2]:
data = pd.read_csv("../data/two_worlds.csv")

In [3]:
data

,main_artist,id,name,popularity,genres,relations
0,Kanye West,30fiiwr2EeZp1tAhzYCmyM,JAY-Z,81,"['east coast hip hop', 'gangster rap', 'hip ho...","[{'id': '3nFkdlSjzX9mRTtwJOzDYB', 'name': 'JAY..."
1,JAY-Z,3PyWEKLWI0vHPmoNrIX0QE,Kid Cudi,77,"['hip hop', 'ohio hip hop', 'pop rap', 'rap']","[{'id': '20qISvAhX20dpIbOOzGK3q', 'name': 'Nas..."
2,Nas,7xTKLpo7UCzXSnlH7fOIoM,Kendrick Lamar,86,"['conscious hip hop', 'hip hop', 'rap', 'west ...","[{'id': '6O2zJ0tId7g07yzHtX0yap', 'name': 'Mob..."
3,Mobb Deep,2yQf6b8hxahZaT5dHlWaB1,A$AP Rocky,79,"['east coast hip hop', 'hip hop', 'rap', 'trap']","[{'id': '30fiiwr2EeZp1tAhzYCmyM', 'name': 'Big..."
4,Mos Def,2Xu7q46Hf02xOoEIm4E1Qs,Baby Keem,75,"['hip hop', 'rap']","[{'id': '67ei8ib6PLT1w3OkhIb4fB', 'name': 'Bla..."
...,...,...,...,...,...,...
2549,Selena Gomez,2S8UlyXW4JjjHcbeg8ddIo,Soft Cell,62,"['new romantic', 'new wave', 'new wave pop', '...","[{'id': '4nDoRrQiYLoBzwC5BhVJzF', 'name': 'Cam..."
2550,Fifth Harmony,702AvACMk5mieXIYlC2Gxx,Adam & The Ants,39,"['new romantic', 'new wave', 'new wave pop']","[{'id': '3e7awlrlDSwF3iM0WBjGMp', 'name': 'Lit..."
2551,Clean Bandit,5NDMothbpdpq2xHqSjrrWn,The Power Station,36,"['dance rock', 'new romantic', 'new wave', 'ne...","[{'id': '1HBjj22wzbscIZ9sEb5dyf', 'name': 'Jon..."
2552,DNCE,62sPt3fswraiEPnKQpAbdE,Mr. Mister,52,"['album rock', 'new romantic', 'new wave pop',...","[{'id': '7gbmX8SsfjEjxDMzBi1ZOL', 'name': 'Joe..."
2553,5 Seconds of Summer,18jZvCsW1PJ4FDQ5gEXuKp,Spandau Ballet,58,"['new romantic', 'new wave', 'new wave pop', '...","[{'id': '4UFShyUQuA8dguoZrqX0jQ', 'name': 'Luk..."

In [21]:
G = nx.DiGraph()

In [42]:
for _, row in data.iterrows():
    main_artist = row["main_artist"]
    main_artist_genres = eval(row["genres"])
    conjunto1 = set(main_artist_genres)
    relations = eval(row["relations"])
    
    G.add_node(main_artist)
    
    for relation in relations:
        artist_relation = relation["name"] 
        artist_genres = relation["genres"].split(", ")
        conjunto2 = set(artist_genres) 
        
        weight = len(conjunto1.intersection(conjunto2)) + 1
        
        G.add_edge(main_artist, artist_relation, weight=weight)

In [48]:
nx.write_gml(G, "../resources/gephi/graph.gml")